### Create Item which color is Red
POST {{host}}/items
Content-Type: application/json

{
  "name": "Example Item Red 1",
  "price": 100,
  "status": "Available",
  "color": "Red",
  "imageUrl": "https://example.com/image.jpg",
  "country": "Thailand",
  "category": "Clothes"
}

### Create Item which color is Blue
POST {{host}}/items
Content-Type: application/json

{
  "name": "Example Item Blue 2",
  "price": 100,
  "status": "Available",
  "color": "Blue",
  "imageUrl": "https://example.com/image.jpg",
  "country": "United States",
  "category": "Decorator"
}
########################################################

### Get all items
# @name getAllItems
GET {{host}}/items

@itemId = {{getAllItems.response.body.0.id}}

### Get Item by Id
GET {{host}}/items/{{itemId}}

########################################################

### Get Items by country
# @name getItemsByCountry
GET {{host}}/items?country=Thailand

### Get Items by category
# @name getItemsByCategory
GET {{host}}/items?category=Clothes

### Get Items by country and category
# @name getItemsByCountryAndCategory
GET {{host}}/items?country=Thailand&category=Clothes

########################################################

### Get Items by status
# @name getItemsByStatus
GET {{host}}/items?status=Available

### Get Items by color
# @name getItemsByColor
GET {{host}}/items?color=Blue

### Get Items by status and color
# @name getItemsByStatusAndColor
GET {{host}}/items?status=Available&color=Red

########################################################

### Update Item
PATCH {{host}}/items/{{itemId}}
Content-Type: application/json

{
  "name": "Javascript Bangkon 2.0",
  "status": "Unavailable"
}

### Delete Item
DELETE {{host}}/items/{{itemId}}